---
services:
# Run gluetun first so it can set up the connection
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ${CONFIG_FOLDER}/gluetun:/gluetun
    environment:
      - PUID=13002
      - PGID=${PGID}
      - TZ=${TZ}
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=wireguard
      - BLOCK_MALICIOUS=off
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - PORT_FORWARD_ONLY=on
      - VPN_PORT_FORWARDING=on
      - VPN_PORT_FORWARDING_UP_COMMAND=/bin/sh -c 'wget -O- --retry-connrefused --post-data "json={\"listen_port\":{{PORTS}}}" http://127.0.0.1:8082/api/v2/app/setPreferences 2>&1'
      - SERVER_COUNTRIES=Netherlands
    ports:
      # Allow ports through for local access (5010 Mousehole, 8082 qbit)
      - 5010:5010
      - 8082:8082

  caddy:
    image: serfriz/caddy-cloudflare-ddns-crowdsec:latest
    container_name: caddy
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    environment:
      - PUID=13001
      - PGID=${PGID}
      - TZ=${TZ}
      - ROOT_DOMAIN=${ROOT_DOMAIN}
      - CLOUDFLARE_API_KEY=${CLOUDFLARE_API_KEY}
      - CROWDSEC_API_KEY=${CROWDSEC_API_KEY}
    volumes:
      - ${APPLICATION_FOLDER}/caddy:/etc/caddy
      - ${APPLICATION_FOLDER}/caddy:/data
      - ${CONFIG_FOLDER}/caddy:/config
      - ${APPLICATION_FOLDER}/caddy/logs:/var/log/caddy
    restart: unless-stopped

  crowdsec:
    image: crowdsecurity/crowdsec:latest
    container_name: crowdsec
    hostname: crowdsec
    ports:
      - 127.0.0.1:8080:8080
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - COLLECTIONS=crowdsecurity/caddy crowdsecurity/http-cve crowdsecurity/whitelist-good-actors crowdsecurity/linux Jgigantino31/calibre-web LePresidente/jellyfin LePresidente/jellyseerr
    volumes:
      - ${CONFIG_FOLDER}/crowdsec:/etc/crowdsec
      - ${APPLICATION_FOLDER}/crowdsec:/var/lib/crowdsec/data/
      - ${APPLICATION_FOLDER}/caddy/logs:/var/log/caddy
      - ${CONFIG_FOLDER}/jellyfin/log:/var/log/jellyfin
      - ${CONFIG_FOLDER}/seerr/logs:/var/log/seerr
      - ${APPLICATION_FOLDER}/calibre/logs:/var/log/calibre
    restart: unless-stopped

  voidauth:
    image: voidauth/voidauth:latest
    container_name: voidauth
    hostname: voidauth
    ports:
      - 3000:3000
    environment:
      - PUID=13005
      - PGID=${PGID}
      - TZ=${TZ}
      - APP_URL=${APP_URL}
      - DB_ADAPTER=sqlite
      - DB_PASSWORD=${DB_PASSWORD}
      - STORAGE_KEY=${STORAGE_KEY}
    volumes:
      - ${CONFIG_FOLDER}/voidauth:/app/config
    restart: unless-stopped

  jellyfin:
    image: ghcr.io/hotio/jellyfin
    container_name: jellyfin
    hostname: jellyfin.local
    ports:
      - 8096:8096
    environment:
      - PUID=13000
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_FOLDER}/jellyfin:/config
      - ${APPLICATION_FOLDER}/jellyfin:/application
      - ${MEDIA_FOLDER}/data:/data
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    restart: unless-stopped

  seerr:
    image: ghcr.io/seerr-team/seerr:latest
    init: true
    container_name: seerr
    hostname: seerr
    user: 13007:${PGID}
    environment:
      - LOG-LEVEL=debug
      - TZ=${TZ}
    volumes:
      - ${CONFIG_FOLDER}/seerr:/app/config
      - ${APPLICATION_FOLDER}/seerr/logs:/var/log/seerr
    ports:
      - 5055:5055
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1
      start_period: 20s
      timeout: 3s
      interval: 60s
      retries: 3
    restart: unless-stopped

  sonarr:
    image: ghcr.io/hotio/sonarr:latest
    container_name: sonarr
    hostname: sonarr
    environment:
      - PUID=13008
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_FOLDER}/sonarr:/config
      - ${MEDIA_FOLDER}/data:/data
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: ghcr.io/hotio/radarr:latest
    container_name: radarr
    hostname: radarr
    environment:
      - PUID=13009
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_FOLDER}/radarr:/config
      - ${MEDIA_FOLDER}/data:/data
    ports:
      - 7878:7878
    restart: unless-stopped

  prowlarr:
    image: ghcr.io/hotio/prowlarr:latest
    container_name: prowlarr
    hostname: prowlarr
    environment:
      - PUID=13010
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_FOLDER}/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  configarr:
    image: ghcr.io/raydak-labs/configarr:latest
    container_name: configarr
    hostname: configarr
    environment:
      - PUID=13011
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_FOLDER}/configarr:/app/config
      - ${APPLICATION_FOLDER}/configarr/cfs:/app/cfs
      - ${APPLICATION_FOLDER}/configarr/repos:/app/repos
      - ${APPLICATION_FOLDER}/configarr/templates:/app/templates

  bazarr:
    image: ghcr.io/hotio/bazarr:latest
    container_name: bazarr
    hostname: bazarr
    environment:
      - PUID=13012
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_FOLDER}/bazarr:/config
      - ${MEDIA_FOLDER}/data:/data
    ports:
      - 6767:6767
    restart: unless-stopped

  booklore:
    image: booklore/booklore:latest
    container_name: booklore
    hostname: booklore
    environment:
      - USER_ID=13013
      - GROUP_ID=${PGID}
      - TZ=${TZ}
      - UMASK=${UMASK}
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_USERNAME=${MARIA_DB_USER}
      - DATABASE_PASSWORD=${MARIA_DB_PASSWORD}
      - BOOKLORE_PORT=6060
    depends_on:
      mariadb:
        condition: service_healthy
    ports:
      - 6060:6060
    volumes:
      - ${APPLICATION_FOLDER}/booklore:/app/data
      - ${MEDIA_FOLDER}/data/media/books:/books
      - ${MEDIA_FOLDER}/data/media/books/ingest:/bookdrop
    restart: unless-stopped

  mariadb:
    image: lscr.io/linuxserver/mariadb:11.4.5
    container_name: mariadb
    hostname: mariadb
    environment:
      - PUID=13013
      - PGID=${PGID}
      - TZ=${TZ}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MARIA_DB_USER}
      - MYSQL_PASSWORD=${MARIA_DB_PASSWORD}
    volumes:
      - ${CONFIG_FOLDER}/booklore/mariadb/config:/config
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "mariadb-admin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 5s
      retries: 10

  shelfmark:
    image: ghcr.io/calibrain/shelfmark:dev
    container_name: shelfmark
    hostname: shelfmark
    environment:
      - PUID=13014
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 8084:8084
    volumes:
      - ${MEDIA_FOLDER}/data/media/books/ingest:/ingest
      - ${MEDIA_FOLDER}/data:/data
      - ${CONFIG_FOLDER}/shelfmark:/config
    restart: unless-stopped

  mousehole:
    image: tmmrtn/mousehole:latest
    network_mode: "service:gluetun"
    environment:
      - PUID=13015
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_FOLDER}/mousehole:/srv/mousehole
    restart: unless-stopped

  qbittorrent:
    image: ghcr.io/hotio/qbittorrent:latest
    container_name: qbittorrent
    # can't use hostname with network_mode
    network_mode: service:gluetun
    depends_on:
      gluetun:
        condition: service_healthy
    environment:
      - PUID=13015
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
      - WEBUI_PORTS=8082/tcp
      - WEBUI_HOST=*
    volumes:
      - ${CONFIG_FOLDER}/qbittorrent:/config
      - ${MEDIA_FOLDER}/data:/data
    restart: unless-stopped
    
  sabnzbd:
    image: ghcr.io/hotio/sabnzbd:latest
    container_name: sabnzbd
    hostname: sabnzbd
    environment:
      - PUID=13016
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
      - WEBUI_PORTS=8081/tcp
    volumes:
      - ${CONFIG_FOLDER}/sabnzbd:/config
      - ${MEDIA_FOLDER}/data:/data
    ports:
      - 8081:8081
    restart: unless-stopped

  notifiarr:
    container_name: notifiarr
    hostname: notifiarr
    image: golift/notifiarr
    environment:
      - PUID=13016
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_FOLDER}/notifiarr:/config
      - /var/run/utmp:/var/run/utmp
      - /etc/machine-id:/etc/machine-id
    ports:
      - 5454:5454
    restart: unless-stopped