---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/
title: Server Status
starturl: https://home.${ROOT_DOMAIN}
disableIndexing: true

layout:
  media:
    style: row
    columns: 4
  services: